language: node_js
node_js:
  - '0.8'
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower protractor
  - npm install
  - bower install
  - ./node_modules/protractor/bin/install_selenium_standalone
  - java -jar selenium/selenium-server-standalone-2.35.0.jar -Dwebdriver.chrome.driver=./selenium/chromedriver &
  - sleep 3

script: grunt test
