language: node_js

node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower protractor
  - npm install
  - bower install
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
  - java -jar selenium-server-standalone-2.31.0.jar > /dev/null &
  - sleep 5

script: grunt test
